# Spam Classification Using different Vectorizer and classifiers

In [22]:
import pandas as pd
import os

senti = pd.read_csv("spam.csv",encoding='cp1252')
#separate the features and the output variable

X = senti['v2']
Y= senti['v1']

In [23]:
X.shape

(5572,)

In [24]:
Y.shape

(5572,)

In [25]:
Y.unique()

array(['ham', 'spam'], dtype=object)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.9, random_state=1111)
#Split into train test

# Using CountVectorizer

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
print("Now with Countvectorizer")
# make a sparse document term matrix using count vectorizer
vect = CountVectorizer( stop_words="english")
# X_train_dtm is the document term matrix
X_train_dtm = vect.fit_transform(X_train)
print(type(X_train_dtm))
X_test_dtm = vect.transform(X_test)

Now with Countvectorizer
<class 'scipy.sparse.csr.csr_matrix'>


In [28]:
vect.vocabulary_

{'canåõt': 1726,
 'wait': 7560,
 'cornwall': 2116,
 'hope': 3620,
 'tonight': 7163,
 'isnåõt': 3885,
 'bad': 1265,
 'itåõs': 3896,
 'rock': 5981,
 'night': 4932,
 'shite': 6276,
 'iåõm': 3906,
 'going': 3288,
 'kip': 4084,
 'good': 3301,
 'speak': 6547,
 'soon': 6503,
 'customer': 2232,
 'service': 6210,
 'representative': 5892,
 'freephone': 3105,
 '0808': 64,
 '145': 328,
 '4742': 549,
 '9am': 803,
 '11pm': 306,
 'won': 7776,
 'guaranteed': 3385,
 '1000': 284,
 'cash': 1760,
 '5000': 583,
 'prize': 5584,
 'yeah': 7889,
 'confirmed': 2061,
 'staying': 6656,
 'weekend': 7651,
 'cramps': 2161,
 'stopped': 6695,
 'sleep': 6398,
 'love': 4374,
 'wine': 7728,
 'dine': 2435,
 'lady': 4135,
 'sunny': 6807,
 'california': 1688,
 'weather': 7634,
 'just': 4015,
 'cool': 2107,
 'know': 4099,
 'mallika': 4479,
 'sherawat': 6260,
 'did': 2410,
 'yesterday': 7903,
 'lt': 4396,
 'url': 7407,
 'gt': 3383,
 'unnecessarily': 7372,
 'hostile': 3638,
 'youåõre': 7926,
 'having': 3489,
 'fun': 3154,
 'to

In [29]:
X_train_dtm

<5014x7972 sparse matrix of type '<class 'numpy.int64'>'
	with 39253 stored elements in Compressed Sparse Row format>

In [30]:
print(X_train_dtm)

  (0, 1726)	1
  (0, 7560)	1
  (0, 2116)	1
  (0, 3620)	1
  (0, 7163)	1
  (0, 3885)	1
  (0, 1265)	1
  (0, 3896)	1
  (0, 5981)	1
  (0, 4932)	2
  (0, 6276)	1
  (0, 3906)	1
  (0, 3288)	1
  (0, 4084)	1
  (0, 3301)	1
  (0, 6547)	1
  (0, 6503)	1
  (1, 2232)	1
  (1, 6210)	1
  (1, 5892)	1
  (1, 3105)	1
  (1, 64)	1
  (1, 328)	1
  (1, 549)	1
  (1, 803)	1
  :	:
  (5011, 6768)	1
  (5012, 7046)	1
  (5012, 6994)	1
  (5012, 581)	1
  (5012, 7397)	1
  (5012, 2195)	1
  (5012, 7649)	2
  (5012, 7721)	1
  (5012, 7653)	1
  (5012, 5390)	1
  (5012, 348)	1
  (5012, 5702)	1
  (5012, 1525)	1
  (5012, 5415)	1
  (5012, 6427)	1
  (5012, 4427)	1
  (5012, 512)	1
  (5012, 383)	1
  (5012, 742)	1
  (5012, 7733)	1
  (5012, 732)	1
  (5012, 3209)	1
  (5013, 2524)	1
  (5013, 1701)	1
  (5013, 6902)	1


In [31]:
# fit the document term matrix and output variable in a Multinomial naive bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

nb.fit(X_train_dtm, y_train)

# predict for test samples document term matrix
y_pred = nb.predict(X_test_dtm)

In [32]:
# print accuracy score and the confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9838709677419355
Confusion matrix:
[[492   3]
 [  6  57]]


In [33]:
#With Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state = 1)
dtc.fit(X_train_dtm, y_train)
y_pred = dtc.predict(X_test_dtm)

In [34]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9713261648745519
Confusion matrix:
[[488   7]
 [  9  54]]


In [35]:
#With Random forest Classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_jobs = -1, random_state = 1)
rfc.fit(X_train_dtm, y_train)
y_pred = rfc.predict(X_test_dtm)

In [36]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9802867383512545
Confusion matrix:
[[494   1]
 [ 10  53]]


In [37]:
#With Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(random_state = 1)
gbc.fit(X_train_dtm, y_train)
y_pred = gbc.predict(X_test_dtm)

In [38]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.967741935483871
Confusion matrix:
[[494   1]
 [ 17  46]]


In [39]:
#With SVM Classifier
from sklearn.svm import SVC
svmm = SVC()
svmm.fit(X_train_dtm,y_train)
y_pred = svmm.predict(X_test_dtm)

In [40]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.982078853046595
Confusion matrix:
[[495   0]
 [ 10  53]]


# Using Tfidf Vectorizer

In [41]:
#Repeat with tfidf vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer( stop_words="english")
# X_train_dtm is the document term matrix
X_train_dtm = vect.fit_transform(X_train)
print(type(X_train_dtm))
X_test_dtm = vect.transform(X_test)

<class 'scipy.sparse.csr.csr_matrix'>


In [42]:
print(X_train_dtm)

  (0, 6503)	0.18548548373462634
  (0, 6547)	0.20234846683504584
  (0, 3301)	0.13995122993810136
  (0, 4084)	0.29501234511849594
  (0, 3288)	0.15071572087204857
  (0, 3906)	0.27184637554763347
  (0, 6276)	0.29501234511849594
  (0, 4932)	0.33338472130438446
  (0, 5981)	0.24122262952660453
  (0, 3896)	0.281461121626694
  (0, 1265)	0.20681127684863582
  (0, 3885)	0.29501234511849594
  (0, 7163)	0.1874329139347131
  (0, 3620)	0.16393439008356292
  (0, 2116)	0.27184637554763347
  (0, 7560)	0.18190118481159612
  (0, 1726)	0.29501234511849594
  (1, 5584)	0.20006313912711313
  (1, 583)	0.2463388177216314
  (1, 1760)	0.20366693232810842
  (1, 284)	0.22553841976172503
  (1, 3385)	0.21861496898602883
  (1, 7776)	0.19587255663531447
  (1, 306)	0.3072664073418279
  (1, 803)	0.30018474199316125
  :	:
  (5011, 1585)	0.47097807461232116
  (5012, 3209)	0.2746741675293432
  (5012, 732)	0.2746741675293432
  (5012, 7733)	0.2746741675293432
  (5012, 742)	0.2746741675293432
  (5012, 383)	0.21891935551026795


In [43]:
 #fit the document term matrix and output variable in a Multinomial naive bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

nb.fit(X_train_dtm, y_train)

# predict for test samples document term matrix
y_pred = nb.predict(X_test_dtm)

In [44]:
# print accuracy score and the confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy with tfidf:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy with tfidf: 0.978494623655914
Confusion matrix:
[[494   1]
 [ 11  52]]


In [45]:
#With Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state = 1)
dtc.fit(X_train_dtm, y_train)
y_pred = dtc.predict(X_test_dtm)

In [46]:
# print accuracy score and the confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy with tfidf:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy with tfidf: 0.974910394265233
Confusion matrix:
[[489   6]
 [  8  55]]


In [47]:
#With Random forest Classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_jobs = -1, random_state = 1)
rfc.fit(X_train_dtm, y_train)
y_pred = rfc.predict(X_test_dtm)

In [48]:
print("Accuracy with tfidf:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy with tfidf: 0.982078853046595
Confusion matrix:
[[495   0]
 [ 10  53]]


In [49]:
#With Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(random_state = 1)
gbc.fit(X_train_dtm, y_train)
y_pred = gbc.predict(X_test_dtm)

In [50]:
print("Accuracy with tfidf:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy with tfidf: 0.9695340501792115
Confusion matrix:
[[495   0]
 [ 17  46]]


In [51]:
#With SVM Classifier
from sklearn.svm import SVC
svmm = SVC()
svmm.fit(X_train_dtm,y_train)
y_pred = svmm.predict(X_test_dtm)

In [52]:
print("Accuracy with tfidf:", accuracy_score(y_test, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy with tfidf: 0.985663082437276
Confusion matrix:
[[495   0]
 [  8  55]]
